name: Deploy to Oracle Cloud Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Use Latest Stable Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'node'

      - name: Install Dependencies
        run: |
          npm prune
          npm uninstall vite
          npm install --save-dev vite
          npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to Oracle Cloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ERC20_token_generator
            git fetch --all
            git reset --hard origin/main
            git clean -f -d
            sudo cp -R /home/ubuntu/ERC20_token_generator/dist/* /var/www/jackhui.com.au/html/ERC20-token-generator/
            sudo chown -R www-data:www-data /var/www/jackhui.com.au/html/ERC20-token-generator/
            #sudo rm -rf /home/ubuntu/ERC20_token_generator
