name: Deploy to Oracle Cloud Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIV_KEY }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIV_KEY }}" | tr -d '\r' | ssh-add -
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Deploy to Oracle Cloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_HOST_USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          private-key: ${{ secrets.SSH_PRIV_KEY }}
          script: |
            # Clone the repository or pull the latest changes
            cd /home/ubuntu
            if [ -d ERC20_token_generator ]; then
              cd ERC20_token_generator
              git pull origin main
            else
              git clone git@github.com:jack-jackhui/ERC20_token_generator.git
              cd ERC20_token_generator
            fi

            # Setup Node.js environment
            source $HOME/.nvm/nvm.sh
            nvm use 21 || nvm install 21

            # Setup .env file
            echo "VITE_ALCHEMY_ID=${{ secrets.VITE_ALCHEMY_ID }}" > .env
            echo "VITE_WALLET_CONNECT_ID=${{ secrets.VITE_WALLET_CONNECT_ID }}" >> .env

            # Install dependencies and build
            npm install
            npm run build

            # Copy the build to the web server directory
            sudo cp -R dist/* /var/www/jackhui.com.au/html/ERC20-token-generator/
            sudo chown -R www-data:www-data /var/www/jackhui.com.au/html/ERC20-token-generator/
            sudo rm -rf $HOME/ERC20_token_generator
