name: Deploy to build-branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify your Node.js version
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      run: |
        git checkout release
        git rm -rf .
        cp -r dist/* .
        git add .
        git commit -m "Deploy new build"
        git push origin release
